relativeURLs = true
title = "Lei Ma"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Ph.D Candidate in Economics, Boston University"
    logo = "images/lei.png"
